### ISSUE TITLE
PrettyEmbed on mobile devices. Bug?

### ISSUE THREAD

**Issue by jenbuzz** [mike-zarandona/PrettyEmbed.js#27]
I'm getting the default YouTube mobile player on mobile devices (useragent set to iPhone 3). No thumbnail - immediately showing the player. Is this the correct behavior? On desktop it works perfectly.

**Comment by boynet** [comment]
must be documented :/ we use this plugin with the idea that we can safely display 20 youtube without slowing down our mobile site, and found out that its somehow worse than with no plugin as now the user also load the thumbanil images and than the youtube iframe :/
