### ISSUE TITLE
open in Lightbox

### ISSUE THREAD

**Issue by samuelhauser** [mike-zarandona/PrettyEmbed.js#32]
is there a possibility to open the video in a lightbox like fancybox?

**Comment by oscarmosh** [comment]
I was looking pretty much for the same, I try to make it work with a couple of plugins but the video still playing in the background with autoplay or if I close the lightbox.

**Comment by mike-zarandona** [comment]
I'm not opposed to this - however I just wonder if this is getting away from the core of PrettyEmbed.  Would it make more sense to use a placeholder image and attach a click event handler to pop open a lightbox to play the video in question?  It sounds to me like this isn't an "embed" at all once the lightbox is introduced.

**Comment by oscarmosh** [comment]
It is true what you say, but for other purposes for example display info + the video, I know it may refer more to a Modal and not a lightbox, my bad. but this is for example, one landing page I made (http://experienciasxcaret.mx/outlet_cancun/)  and if you click an item you will see an embedded video, but I was unable to change the embedded image and maintain the responsiveness on it.  It would be cool to use prettyembed, but my problem was that the video still playing in the background.
